services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_DB=loan_db'
      - 'POSTGRES_USER=loan_user'
      - 'POSTGRES_PASSWORD=REDACTED'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: